version: 2.1
jobs:
  deploy-production-nha:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5a:30:fa:15:ba:ae:be:9c:9b:9a:61:e5:65:0d:ec:3a"
      - run:
          name: Access server nha
          command: ssh -oStrictHostKeyChecking=no root@45.76.160.102 '/deploy.sh'
workflows:
  deploy-production:
    jobs:
      - deploy-production-nha:
          filters:
            branches:
              only:
                - master
