version: 2.1
jobs:
  deploy-production-nha:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a7:43:06:c4:3b:82:39:7b:0e:19:d5:33:2e:1c:37:e3"
      - run:
          name: Access server nha
          command: ssh -oStrictHostKeyChecking=no root@45.76.160.102 scp -r wp/wp-content/themes/kienthucthuvi root@45.76.160.102:/home/admin/web/kienthucthuvi.org/public_html/wp-content/themes/
workflows:
  deploy-production:
    jobs:
      - deploy-production-nha:
          filters:
            branches:
              only:
                - master
