
version: 2.1
jobs:   
  deploy-production-nha:
    docker: 
      - image: circleci/php:7.4-node-browsers
    steps:
      - add_ssh_keys:
            fingerprints:
              - "50:8e:7b:fa:f7:86:16:ab:46:42:09:30:65:0c:dc:99"
      - run:
          name: Deploy server nha nha
          command: scp -r wp/wp-content/themes/kienthucthuvi root@45.76.160.102:/home/admin/web/kienthucthuvi.org/public_html/wp-content/themes/

workflows:
  deploy-production:
    jobs:
      - deploy-production-nha